// Usage Alerts — threshold monitoring for token budgets.
//
// Evaluates usage against configurable thresholds and produces alerts:
// - **Warn** (80%)     — approaching limit, take action soon
// - **Critical** (95%) — very close to limit, imminent blocking
// - **Blocked** (100%) — budget exhausted, requests are denied
//
// ## Integration
// ```ignore
// let manager = AlertManager::new(db);
// let usage = tracker.get_usage(&user_id, UsagePeriod::LastDay).await?;
// let alerts = manager.check_thresholds(&user_id, &usage);
// if manager.should_block(&user_id) {
//     return Err("blocked by budget");
// }
// ```

use std::sync::Arc;

use serde::Serialize;
use uuid::Uuid;

use crate::governance::database::{Database, DatabaseError};
use crate::governance::tracking::UsageSummary;
use rusqlite::params;
use crate::governance::quotas::BudgetPeriod;

// ---------------------------------------------------------------------------
// Severity
// ---------------------------------------------------------------------------

/// Alert severity level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum Severity {
    /// Usage is approaching the limit (≥80%).
    Warn,
    /// Usage is critically close to the limit (≥95%).
    Critical,
}

// ---------------------------------------------------------------------------
// Alert types
// ---------------------------------------------------------------------------

/// Category of budget alert.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub enum AlertType {
    /// Hourly budget threshold crossed.
    HourlyBudget,
    /// Daily budget threshold crossed.
    DailyBudget,
    /// Monthly budget threshold crossed.
    MonthlyBudget,
    /// All budgets combined (global check).
    GlobalBudget,
}

// ---------------------------------------------------------------------------
// Alert struct
// ---------------------------------------------------------------------------

/// A single alert generated by threshold monitoring.
#[derive(Debug, Clone, Serialize)]
pub struct Alert {
    pub alert_type: AlertType,
    pub message: String,
    pub severity: Severity,
    /// The percentage of budget consumed that triggered this alert (0–100).
    pub usage_pct: f64,
}

// ---------------------------------------------------------------------------
// Threshold constants
// ---------------------------------------------------------------------------

/// Fraction of budget consumed before a `Warn` alert fires.
pub const THRESHOLD_WARN: f64 = 0.80;

/// Fraction of budget consumed before a `Critical` alert fires.
pub const THRESHOLD_CRITICAL: f64 = 0.95;

/// Fraction of budget consumed before `should_block` returns `true`.
pub const THRESHOLD_BLOCK: f64 = 1.00;

// ---------------------------------------------------------------------------
// AlertManager
// ---------------------------------------------------------------------------

/// Monitors token usage against budget thresholds and generates alerts.
///
/// Uses the governance database to retrieve budget limits and provides
/// both synchronous check methods and an async awareness of usage data.
pub struct AlertManager {
    pub db: Arc<Database>,
    /// Optional overrides for alert thresholds (percentage, 0.0–1.0).
    /// If `None`, defaults (`THRESHOLD_WARN`, `THRESHOLD_CRITICAL`) are used.
    pub thresholds: Option<AlertThresholds>,
}

/// Custom threshold percentages.
#[derive(Debug, Clone)]
pub struct AlertThresholds {
    /// Warn at this fraction (default 0.80).
    pub warn: f64,
    /// Critical at this fraction (default 0.95).
    pub critical: f64,
}

impl Default for AlertThresholds {
    fn default() -> Self {
        Self {
            warn: THRESHOLD_WARN,
            critical: THRESHOLD_CRITICAL,
        }
    }
}

impl AlertManager {
    pub fn new(db: Arc<Database>) -> Self {
        Self {
            db,
            thresholds: None,
        }
    }

    /// Create an `AlertManager` with custom threshold percentages.
    pub fn with_thresholds(db: Arc<Database>, thresholds: AlertThresholds) -> Self {
        Self {
            db,
            thresholds: Some(thresholds),
        }
    }

    /// Return the effective threshold values (custom or default).
    fn thresholds(&self) -> AlertThresholds {
        self.thresholds.clone().unwrap_or_default()
    }

    /// Evaluate usage against budget limits and return active alerts.
    ///
    /// Compares the provided `UsageSummary` against the user's budget config
    /// and generates alerts for any period where usage exceeds the configured
    /// warning or critical thresholds.
    ///
    /// This is a read-only operation — it never modifies the database.
    pub fn check_thresholds(
        &self,
        user_id: &str,
        usage: &UsageSummary,
    ) -> Result<Vec<Alert>, DatabaseError> {
        let config = self.db.get_budget_config(user_id)?;
        let thresholds = self.thresholds();
        let mut alerts = Vec::new();

        // Check hourly budget
        if config.tokens_per_hour > 0 {
            let pct = usage.total_tokens as f64 / config.tokens_per_hour as f64;
            if let Some(alert) = self.check_single(pct, &thresholds, AlertType::HourlyBudget) {
                alerts.push(alert);
            }
        }

        // For daily/monthly, we need broader usage. Since the UsageSummary
        // provided here may be for any period, we also check against the
        // daily and monthly budgets separately using dedicated DB queries.

        // We use blocking calls via the Database directly since we're already
        // in a sync context. The caller's async context handles spawn_blocking.

        // Daily check
        if config.tokens_per_day > 0 {
            let used = self.db.query_tokens_in_window(
                user_id,
                BudgetPeriod::Daily.window_start(),
                chrono::Utc::now(),
            )?;
            let pct = used as f64 / config.tokens_per_day as f64;
            if let Some(alert) = self.check_single(pct, &thresholds, AlertType::DailyBudget) {
                alerts.push(alert);
            }
        }

        // Monthly check
        if config.tokens_per_month > 0 {
            let used = self.db.query_tokens_in_window(
                user_id,
                BudgetPeriod::Monthly.window_start(),
                chrono::Utc::now(),
            )?;
            let pct = used as f64 / config.tokens_per_month as f64;
            if let Some(alert) = self.check_single(pct, &thresholds, AlertType::MonthlyBudget) {
                alerts.push(alert);
            }
        }

        Ok(alerts)
    }

    /// Determine whether the user should be blocked from making requests.
    ///
    /// Returns `true` if any budget period has reached or exceeded 100%
    /// utilization.
    pub fn should_block(&self, user_id: &str) -> Result<bool, DatabaseError> {
        let config = self.db.get_budget_config(user_id)?;
        let now = chrono::Utc::now();

        if config.tokens_per_hour > 0 {
            let used = self
                .db
                .query_tokens_in_window(user_id, BudgetPeriod::Hourly.window_start(), now)?;
            if used >= config.tokens_per_hour {
                return Ok(true);
            }
        }

        if config.tokens_per_day > 0 {
            let used = self
                .db
                .query_tokens_in_window(user_id, BudgetPeriod::Daily.window_start(), now)?;
            if used >= config.tokens_per_day {
                return Ok(true);
            }
        }

        if config.tokens_per_month > 0 {
            let used = self
                .db
                .query_tokens_in_window(user_id, BudgetPeriod::Monthly.window_start(), now)?;
            if used >= config.tokens_per_month {
                return Ok(true);
            }
        }

        Ok(false)
    }

    // ------------------------------------------------------------------
    // Internal helpers
    // ------------------------------------------------------------------

    /// Check a single usage percentage against thresholds and return an
    /// alert if it crosses a boundary.
    fn check_single(
        &self,
        usage_pct: f64,
        thresholds: &AlertThresholds,
        alert_type: AlertType,
    ) -> Option<Alert> {
        let label = match &alert_type {
            AlertType::HourlyBudget => "hourly",
            AlertType::DailyBudget => "daily",
            AlertType::MonthlyBudget => "monthly",
            AlertType::GlobalBudget => "global",
        };

        if usage_pct >= THRESHOLD_BLOCK {
            Some(Alert {
                alert_type,
                severity: Severity::Critical,
                usage_pct: usage_pct * 100.0,
                message: format!(
                    "{} budget exhausted ({:.1}% used) — requests are being blocked",
                    label,
                    usage_pct * 100.0
                ),
            })
        } else if usage_pct >= thresholds.critical {
            Some(Alert {
                alert_type,
                severity: Severity::Critical,
                usage_pct: usage_pct * 100.0,
                message: format!(
                    "{} budget critically low ({:.1}% used) — blocking imminent",
                    label,
                    usage_pct * 100.0
                ),
            })
        } else if usage_pct >= thresholds.warn {
            Some(Alert {
                alert_type,
                severity: Severity::Warn,
                usage_pct: usage_pct * 100.0,
                message: format!(
                    "{} budget running low ({:.1}% used) — consider reducing usage",
                    label,
                    usage_pct * 100.0
                ),
            })
        } else {
            None
        }
    }
}

// ---------------------------------------------------------------------------
// Database alert configuration methods
// ---------------------------------------------------------------------------

impl Database {
    /// Record an alert in the database for historical tracking.
    pub fn insert_alert(
        &self,
        user_id: &str,
        alert_type: &str,
        threshold: i32,
    ) -> Result<(), DatabaseError> {
        let conn = self.conn.lock().unwrap();
        let id = Uuid::new_v4().to_string();

        conn.execute(
            "INSERT INTO alerts (id, user_id, alert_type, threshold, enabled)
             VALUES (?1, ?2, ?3, ?4, 1)
             ON CONFLICT(id) DO NOTHING",
            params![id, user_id, alert_type, threshold],
        )?;

        Ok(())
    }

    /// List all enabled alerts for a user.
    pub fn list_alerts(&self, user_id: &str) -> Result<Vec<(String, String, i32)>, DatabaseError> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, alert_type, threshold
             FROM alerts
             WHERE user_id = ?1 AND enabled = 1
             ORDER BY threshold DESC",
        )?;

        let rows = stmt.query_map(params![user_id], |row| {
            let id: String = row.get(0)?;
            let alert_type: String = row.get(1)?;
            let threshold: i32 = row.get(2)?;
            Ok((id, alert_type, threshold))
        })?;

        let mut alerts = Vec::new();
        for row in rows {
            alerts.push(row?);
        }
        Ok(alerts)
    }

    /// Disable an alert by its id.
    pub fn disable_alert(&self, alert_id: &str) -> Result<(), DatabaseError> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "UPDATE alerts SET enabled = 0 WHERE id = ?1",
            params![alert_id],
        )?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::governance::Database;

    fn test_db() -> Database {
        let tmp = std::env::temp_dir().join(format!("cg_alt_{}.db", Uuid::new_v4()));
        let path = tmp.to_str().unwrap().to_string();
        tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(Database::open_or_create(&path))
            .expect("test db creation")
    }

    #[test]
    fn test_threshold_constants() {
        assert_eq!(THRESHOLD_WARN, 0.80);
        assert_eq!(THRESHOLD_CRITICAL, 0.95);
        assert_eq!(THRESHOLD_BLOCK, 1.00);
    }

    #[test]
    fn test_check_thresholds_no_budget() {
        let db = test_db();
        let user = db.create_user("no_budget", "no_budget@example.com").unwrap();

        let manager = AlertManager::new(Arc::new(db));
        let usage = UsageSummary::empty();

        let alerts = manager
            .check_thresholds(&user.id, &usage)
            .expect("check_thresholds should succeed");
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_check_thresholds_below_warn() {
        let db = test_db();
        let user = db.create_user("below_warn", "below_warn@example.com").unwrap();
        db.set_budget_config(&user.id, 1000, 0, 0).unwrap();

        // Usage at 50% of hourly budget
        let mut usage = UsageSummary::empty();
        usage.total_tokens = 500;

        let manager = AlertManager::new(Arc::new(db));
        let alerts = manager
            .check_thresholds(&user.id, &usage)
            .expect("check_thresholds should succeed");
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_check_thresholds_warn() {
        let db = test_db();
        let user = db.create_user("warn_user", "warn@example.com").unwrap();
        db.set_budget_config(&user.id, 1000, 0, 0).unwrap();

        // Insert usage at 85% of hourly budget
        db.insert_token_usage(&user.id, "gpt-4o", "openai", 850, 0, 0.01)
            .unwrap();

        let mut usage = UsageSummary::empty();
        usage.total_tokens = 850;

        let manager = AlertManager::new(Arc::new(db));
        let alerts = manager
            .check_thresholds(&user.id, &usage)
            .expect("check_thresholds should succeed");
        assert!(!alerts.is_empty());

        let warn_alerts: Vec<_> = alerts.iter().filter(|a| a.severity == Severity::Warn).collect();
        assert!(!warn_alerts.is_empty());
    }

    #[test]
    fn test_check_thresholds_critical() {
        let db = test_db();
        let user = db
            .create_user("critical_user", "critical@example.com")
            .unwrap();
        db.set_budget_config(&user.id, 1000, 0, 0).unwrap();

        // Usage at 97% of hourly budget
        db.insert_token_usage(&user.id, "gpt-4o", "openai", 970, 0, 0.01)
            .unwrap();

        let mut usage = UsageSummary::empty();
        usage.total_tokens = 970;

        let manager = AlertManager::new(Arc::new(db));
        let alerts = manager
            .check_thresholds(&user.id, &usage)
            .expect("check_thresholds should succeed");
        assert!(!alerts.is_empty());

        let critical_alerts: Vec<_> = alerts
            .iter()
            .filter(|a| a.severity == Severity::Critical)
            .collect();
        assert!(!critical_alerts.is_empty());
    }

    #[test]
    fn test_should_block_false_when_under_limit() {
        let db = test_db();
        let user = db
            .create_user("no_block", "no_block@example.com")
            .unwrap();
        db.set_budget_config(&user.id, 1000, 0, 0).unwrap();
        db.insert_token_usage(&user.id, "gpt-4o", "openai", 500, 0, 0.01)
            .unwrap();

        let manager = AlertManager::new(Arc::new(db));
        let blocked = manager.should_block(&user.id).unwrap();
        assert!(!blocked);
    }

    #[test]
    fn test_should_block_true_when_exceeded() {
        let db = test_db();
        let user = db.create_user("blocked", "blocked@example.com").unwrap();
        db.set_budget_config(&user.id, 100, 0, 0).unwrap();
        db.insert_token_usage(&user.id, "gpt-4o", "openai", 120, 0, 0.01)
            .unwrap();

        let manager = AlertManager::new(Arc::new(db));
        let blocked = manager.should_block(&user.id).unwrap();
        assert!(blocked);
    }

    #[test]
    fn test_should_block_unlimited_budget() {
        let db = test_db();
        let user = db
            .create_user("unlimited_block", "unlimited_block@example.com")
            .unwrap();

        // No budget = never blocked
        let manager = AlertManager::new(Arc::new(db));
        let blocked = manager.should_block(&user.id).unwrap();
        assert!(!blocked);
    }

    #[test]
    fn test_should_block_multiple_periods() {
        let db = test_db();
        let user = db
            .create_user("multi_period", "multi_period@example.com")
            .unwrap();
        db.set_budget_config(&user.id, 1000, 500, 10000).unwrap();

        // Exceeds daily but not hourly or monthly
        db.insert_token_usage(&user.id, "gpt-4o", "openai", 600, 0, 0.01)
            .unwrap();

        let manager = AlertManager::new(Arc::new(db));
        let blocked = manager.should_block(&user.id).unwrap();
        assert!(blocked, "should block because daily limit exceeded");
    }

    #[test]
    fn test_custom_thresholds() {
        let db = test_db();
        let user = db
            .create_user("custom_thresh", "custom_thresh@example.com")
            .unwrap();
        db.set_budget_config(&user.id, 1000, 0, 0).unwrap();

        // Custom thresholds: warn at 50%, critical at 75%
        let custom = AlertThresholds {
            warn: 0.50,
            critical: 0.75,
        };
        let manager = AlertManager::with_thresholds(Arc::new(db), custom);

        let mut usage = UsageSummary::empty();
        usage.total_tokens = 600; // 60% → above custom warn (50%)

        let alerts = manager
            .check_thresholds(&user.id, &usage)
            .expect("check_thresholds should succeed");
        assert!(!alerts.is_empty());
        assert_eq!(alerts[0].severity, Severity::Warn);
    }

    #[test]
    fn test_insert_and_list_alerts() {
        let db = test_db();
        let user = db.create_user("alert_db", "alert_db@example.com").unwrap();

        db.insert_alert(&user.id, "hourly_budget", 80).unwrap();
        db.insert_alert(&user.id, "daily_budget", 95).unwrap();

        let alerts = db.list_alerts(&user.id).unwrap();
        assert_eq!(alerts.len(), 2);
    }

    #[test]
    fn test_disable_alert() {
        let db = test_db();
        let user = db
            .create_user("disable_alert", "disable_alert@example.com")
            .unwrap();

        db.insert_alert(&user.id, "hourly_budget", 80).unwrap();
        let alerts = db.list_alerts(&user.id).unwrap();
        assert_eq!(alerts.len(), 1);

        db.disable_alert(&alerts[0].0).unwrap();
        let alerts_after = db.list_alerts(&user.id).unwrap();
        assert_eq!(alerts_after.len(), 0);
    }
}
